# This is a basic workflow to help you get started with Actions

name: Hello World Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  [push, workflow_dispatch]
  # paths:
  #   # this workflow will only run if a .java file is pushed.
  #   - "**.java"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: Build Step
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: |
          git clone --quiet https://github.com/junk33/hello-world-test.git
          ./hello-world-test/build-with-maven.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Compile-Run-Report
          path: out
          retention-days: 3
      - name: Generate Warning Annotations
        run: |
          text="This is a Warning from the YML file as Github Action"
          echo "::warning file=README.md,line=1,col=5::$text"
          echo "::error file=README.md,line=15,col=3::Sample-Error Message"
          echo "::group::A Group"
          echo "::warning file=README.md,line=1,col=5::A 1"
          echo "::warning file=README.md,line=3,col=5::A 2"
          echo "::warning file=README.md,line=5,col=5::A 3"
          echo "::endgroup::"
