# This is a basic workflow to help you get started with Actions

name: Hello World Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  [push, workflow_dispatch]
  # paths:
  #   # this workflow will only run if a .java file is pushed.
  #   - "**.java"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    name: Build Step
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 1.8

      - name: Build with Maven
        run: |
          git clone --quiet https://github.com/junk33/hello-world-test.git
          ./hello-world-test/build-with-maven.py

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Compile-Run-Report
      #     path: out
      #     retention-days: 3

      # https://github.com/yuzutech/annotations-action
      # - name: Annotate
      #   uses: yuzutech/annotations-action@v0.1.0
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     title: "lint"
      #     input: "./out/annotations.json"
      # https://github.com/agyemanjp/ci-checks-action
      - name: Annotate Checks
        uses: agyemanjp/ci-checks-action@2.0.4
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          checks: '[
            {
            "name": "lint",
            "fileName": "./out/annotations.json",
            "prChangesOnly": true
            },
            {
            "name": "test",
            "fileName": "./out/annotations.json",
            "prChangesOnly": false
            }
            ]'
